name: Trigger auto deployment for dwittechaccountservicewebapi-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dwittechaccountservicewebapi-app-AutoDeployTrigger-d9f98994-c38d-48c2-95f6-db53b7c2a064.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: dotnetcoreapi20230130123723.azurecr.io
          username: ${{ secrets.DWITTECHACCOUNTSERVICEWEBAPIAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.DWITTECHACCOUNTSERVICEWEBAPIAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dotnetcoreapi20230130123723.azurecr.io/dwittechaccountservicewebapi-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DWITTECHACCOUNTSERVICEWEBAPIAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dwittechaccountservicewebapi-app -g dwit-tech --server dotnetcoreapi20230130123723.azurecr.io --username  ${{ secrets.DWITTECHACCOUNTSERVICEWEBAPIAPP_REGISTRY_USERNAME }} --password ${{ secrets.DWITTECHACCOUNTSERVICEWEBAPIAPP_REGISTRY_PASSWORD }}
            az containerapp update -n dwittechaccountservicewebapi-app -g dwit-tech --image dotnetcoreapi20230130123723.azurecr.io/dwittechaccountservicewebapi-app:${{ github.sha }}
